/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.cabinvoicegenerator;

public class Main {

public static void main (String args[])
{
	System.out.println("Welcome to Cab invoice generator program");
	}
}
